# post http://localhost:80/reset-password
# Content-Type: application/json

# {
#   "inputEmail": "johndoe@gmail.com"
# }

# test data untuk registration
# POST http://localhost:80/api/registrasi-umkm
# Content-Type: application/json
# {
#     "nama_lengkap": "Darryl Rambi",
#     "nomor_telepon": "0812346567890",
#     "alamat": "Jl. Sudirman No. 123, Jakarta",
#     "username": "darryl.rambi",
#     "email": "darrylrambi@gmail.com",
#     "password": "secureP@ssword123",
#     "nama_usaha": "Darryl's Deal",
#     "NIK_KTP": 1234567891
# }

POST http://localhost:80/api/verifikasi-otp
Content-Type: application/json

{
  "email": "darrylf.rambi@gmail.com",
  "password": "secureP@ssword123"
}